services:
  - type: web
    name: stockpulse-dashboard
    runtime: node
    rootDir: web-dashboard
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3001
      - key: KAFKA_BROKER
        value: localhost:9092
